server:
  port: 8091

spring:
  application:
    name: ACTIONSERVICE

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: Eidiko
    password: sarasu10
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true