server:
  port: 8091

spring:
  application:
    name: Aug20_SpringBootApplication
  oracle:
    datasource:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: Eidiko
      password: sarasu10
      driver-class-name: oracle.jdbc.OracleDriver

  mysql:
    datasource:
      url: jdbc:mysql://localhost:3306/Eidiko
      username: root
      password: sarasu10
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true