server:
  port: 8090

spring:
  application:
    name: SpringBoot1
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: Eidiko
    password: sarasu10
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Configuration Properties()

bank:
  cluster:
    details:
      name: HDFC
      ifsc: HDFC1234
      branch: Raidurgam
      city: Hyderabad
      state: Telangana
    account:
      account-number: 1234567890
      balance: 1000000